### ISSUE TITLE
DA-6569-3590-0263

### ISSUE THREAD

**Issue by jpgxxxxxxxx** [Ixaruz/Luna-Archive-of-Dreams#110]
Thank you so much in advance!

**Comment by somegenie** [comment]
Does not exist, sorry...

**Comment by jpgxxxxxxxx** [comment]
Thank you for checking.. May I ask for this one instead? DA-6013-3531-5435

I really appreciate your time and effort!

**Comment by somegenie** [comment]
Odd... It's giving me an "unknown revision" error. Judging by that label, perhaps that dream is from a different ACNH version and needs to be updated. Or if you really want, I could try and find out which version it is by using different versions of HorizonCrypt...

**Comment by jpgxxxxxxxx** [comment]
I am really sorry for giving you so much trouble. Is it hard to do that? If it will take up so much of your time, please disregard my request. Thanks again!

**Comment by Ixaruz** [comment]
the unknown revision error has nothing to do with the dream.

 I will dump it for you in a bit @jpgxxxxxxxx, Dont worry. you aren't giving anyone too much trouble.

**Comment by Ixaruz** [comment]
doneso
