### ISSUE TITLE
Dream Request

### ISSUE THREAD

**Issue by xiaumiao** [Ixaruz/Luna-Archive-of-Dreams#115]
Hi, please may I request these two island dumps QQ I searched to check that they weren't already in the archive so I hope I'm right aaaa
DA-5143-7350-0978
DA-8590-5698-2285

thankyousosososomuchilysm

**Comment by Ixaruz** [comment]
Hellow, since the 2.0 update just released, please allow us some extra time. We'll try our best to get the dumps soon.

**Comment by xiaumiao** [comment]
weeh, sure no rush! take all the time you need, thank you for even doing this ! <33
 _sending all the hugs and support_

**Comment by Ixaruz** [comment]
there u go, stay safe. <3
