### ISSUE TITLE
Dream Request

### ISSUE THREAD

**Issue by SandeepKharoud** [Ixaruz/Luna-Archive-of-Dreams#126]
**Please enter the Dream Address here:**
DA-7477-5171-3499

**Comment by somegenie** [comment]
It's dumped, thanks for the request! Just to clarify, though, most sources with this Dream Address show an old version of the island, so I want to be sure the island you're looking for is currently in Winter?

**Comment by SandeepKharoud** [comment]
Yes the winter one is the one.

**Comment by somegenie** [comment]
Okay, that's all, then.
