### ISSUE TITLE
Dream Request

### ISSUE THREAD

**Issue by Jouslyn** [Ixaruz/Luna-Archive-of-Dreams#128]
**Please enter the Dream Address here:**
DA-8297-5906-8199
DA-1627-5603-6916
𝙳𝙰-𝟺𝟾𝟼𝟶-𝟺𝟽𝟼𝟷-𝟼𝟺𝟷𝟼

**Comment by somegenie** [comment]
The first dream, "umbrA", is already in the archive under 2.0.0. The second one is also in the archive, but not under 2.0.0. I'm not sure yet whether or not it should be re-added in the 2.0.0 folder. The third dream has been dumped and added.

**Comment by somegenie** [comment]
The second dream hasn't been updated since the last time it was added to the archive. There are actually two dreams in the archive with that same Dream Address and timestamp, one in 1.10.0 and one in 1.11.0; doing this would create a third duplicate. Try using one of those 2 and updating it instead.

**Comment by Jouslyn** [comment]
I got this issue and it didnt work. May I ask how to fix it?

**Comment by Jouslyn** [comment]
Unhandled Exception: System.IndexOutOfRangeException: Unknown revision!
FileHeaderInfo { Major = 1669400217, Minor = 1027818944, Unk1 = 43709, HeaderRevision = 6597, Unk2 = 13993, SaveRevision = 48085 }
   at NHSE.Core.MainSaveOffsets.GetOffsets(FileHeaderInfo Info)
   at NHSE.Core.MainSave..ctor(String folder)
   at NHSE.Core.HorizonSave..ctor(String folder)
   at PogCrypt.ConsoleApp.Program.fixhashes(String& directory)
   at PogCrypt.ConsoleApp.Program.fixhashes(String& directory)
   at PogCrypt.ConsoleApp.Program.TryExecute(String[] args)
   at PogCrypt.ConsoleApp.Program.Main(String[] args)

**Comment by somegenie** [comment]
Where is that error from?

**Comment by Jouslyn** [comment]
cmd - at the end of encrypt process

**Comment by somegenie** [comment]
All dreams in the archive should already be encrypted.

**Comment by Jouslyn** [comment]
Ohhh. I didn't know. Thank you so much for that!

**Comment by somegenie** [comment]
All good, tell me if anything else comes up.
