### ISSUE TITLE
Dream Request

### ISSUE THREAD

**Issue by hugo-twi** [Ixaruz/Luna-Archive-of-Dreams#150]
1. Okinawa Island
DA: 8538 – 5723 – 6984

**Comment by hugo-twi** [comment]
2. Hanami Crossing
Fantasy | Feudal Japan
DA 4231-3384-5136

**Comment by hugo-twi** [comment]
and if you can DA-5533-0273-2398 . Thanks you so much

**Comment by somegenie** [comment]
All three of these are already in the archive, though the last one has been updated since its archival so it was added to the 2.0.0 folder. The others can be played by restoring them in JKSV and updating when prompted by the game.
