### ISSUE TITLE
Request: DA Dumps 

### ISSUE THREAD

**Issue by domxnik** [Ixaruz/Luna-Archive-of-Dreams#20]
Hey! I'd like to request the Dumps for 3980-0406-0110 and 0731-2081-5960. I'd do it by myself but since my console had been banned a while ago I'm not able to do it, I hope it doesn't bother you.

Thx in advance!

**Comment by Ixaruz** [comment]
Heyo, i gotta wait until atmosphere/hecate are updated to support switch firmware 12.0.0, after that I'll make sure to dump it :)

**Comment by Ixaruz** [comment]
Done, you can find the dumps in the commit referenced.
