### ISSUE TITLE
Import dumps to my player's dreams without Internet?

### ISSUE THREAD

**Issue by MichaelBui** [Ixaruz/Luna-Archive-of-Dreams#30]
I will put up my question here as I believe many other people will have the same question:
"How to import the dream dump/save files into my player's dreams and access them during the game *without* an Internet connection"

I've been using NHSE but I don't know if NHSE has this feature
I've been using JKSV but then it's just loading another save file? I want to keep my customized players (me & my 7yo daughter) with my beloved villagers...
I'm looking for a method to NOT replacing my current island, just access via dreams when my players go to sleep (still keep my current island) so that my 7yo daughter can play on the current island but able to "visit" the dream islands easily.

Thank you so much 🙏

**Comment by Ixaruz** [comment]
I assume it would require more intense reverse engineering to make it possible to essentially "inject" a dream island without going online in the process.

Only option so far is just loading dumps and then switching back to your personal save when you're done looking around.
I'm sorry, but I doubt I can make that happen with my current knowledge of the game.

**Comment by MichaelBui** [comment]
Totally understood. Really appreciate your help & efforts!
