### ISSUE TITLE
Dump request : 5038-2382-3756

### ISSUE THREAD

**Issue by lutinotmalin** [Ixaruz/Luna-Archive-of-Dreams#36]
Hey mate !

I'd love to have a try with this island... You've already dumped one island for me like one year ago, though I'm asking for your help once again, since I can't do it myself with my Linux system. Could you please dump it for me ?

Miarain - 5038-2382-3756

You're the best. Can't wait for your answer.

Cheers,

lutinotmalin

**Comment by Ixaruz** [comment]
it's definitely possible to do on Linux, but nonetheless I'll put it in the archive for you.
