### ISSUE TITLE
Unhandled exception error when encrypting dream island

### ISSUE THREAD

**Issue by fall-fawn** [Ixaruz/Luna-Archive-of-Dreams#53]
![image](https://user-images.githubusercontent.com/89107137/129804408-e9ce8606-ac71-4935-8def-51d03dbf33f5.png)
HI, i'm having this error with all of the dream islands I've been trying to encrypt. I'm using everything that is up to date, and the encrypted files won't open on NHSE or work at all in-game. Is there anything I can do to solve this issue?

Unhandled Exception: System.IndexOutOfRangeException: Unknown revision!
FileHeaderInfo { Major = 1666898533, Minor = 579558984, Unk1 = 12644, HeaderRevision = 41797, Unk2 = 59016, SaveRevision = 7336 }
   at NHSE.Core.MainSaveOffsets.GetOffsets(FileHeaderInfo Info)
   at NHSE.Core.MainSave..ctor(String folder)
   at NHSE.Core.HorizonSave..ctor(String folder)
   at PogCrypt.ConsoleApp.Program.fixhashes(String& directory)
   at PogCrypt.ConsoleApp.Program.fixhashes(String& directory)
   at PogCrypt.ConsoleApp.Program.TryExecute(String[] args)
   at PogCrypt.ConsoleApp.Program.Main(String[] args)

**Comment by Ixaruz** [comment]
It's likely that the save file you're trying to encrypt is already encrypted.
(This archive only houses encrypted saves because that is the norm for both the game and NHSE)

**Comment by fall-fawn** [comment]
I was following your Luna guide on youtube and thought I had to encrypt the file first before loading it into the game. I didn't realize that the archived dream dumps were already good to go. Thank you for answering! Everything works as intended now.
