### ISSUE TITLE
Personal Island Dump

### ISSUE THREAD

**Issue by Hoobens** [Ixaruz/Luna-Archive-of-Dreams#58]

**Comment by Hoobens** [comment]
Hi! Can you dump this island for me, please?

DA 5336-1102-3158

Thank you very much <3

**Comment by Ixaruz** [comment]
doneso and thanks!

**Comment by Hoobens** [comment]
Will it be possible to play online with this save using the main villager?

Thank you so much <3

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em seg., 30 de ago. de 2021 às 18:45, Emil B. ***@***.***>
escreveu:
