### ISSUE TITLE
Dump request

### ISSUE THREAD

**Issue by ineffablesay** [Ixaruz/Luna-Archive-of-Dreams#6]
Hi - is it possible to have this address dumped?

DA-9491-3745-1128 - Land of Oo

**Comment by Ixaruz** [comment]
Hello, sorry for the long wait time!

The save wasn't tested yet but it is assumed working by my critical eye. You can find your save here:
https://github.com/Ixaruz/Luna-Archive-of-Dreams/tree/master/1.9.0

I had to zip it, due to github being a total piece of trash on phone.

**Comment by ineffablesay** [comment]
no worries - it's a blessing you even bother doing this 👏🏻 I'll let you know if it doesn't work for me

**Comment by Ixaruz** [comment]
> no worries - it's a blessing you even bother doing this 👏🏻 I'll let you know if it doesn't work for me 

I assume you tried by now and... Does it work? 😅

**Comment by ineffablesay** [comment]
all is well - thank you once more ✌🏻
