### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by haselino** [Ixaruz/Luna-Archive-of-Dreams#67]
![pr](https://user-images.githubusercontent.com/77906227/132913554-4bee4f7e-fa1b-4529-8eaf-8ef77993cbe4.png)

What does it means?

**Comment by Ixaruz** [comment]
Update NHSE.

**Comment by haselino** [comment]
Ty.

**Comment by haselino** [comment]
How you update nhse?

**Comment by haselino** [comment]
I have it tysm.
