### ISSUE TITLE
Corrupted Save game

### ISSUE THREAD

**Issue by LuzRod123** [Ixaruz/Luna-Archive-of-Dreams#68]
When i launch my acnh with the savegame from JKSV it says that the save game is corrupted and  it ask me if i want to create new data any solutions ?

**Comment by LuzRod123** [comment]
but i have no date folder when i extract the zip from dowgift it give me a folder named 10.11.2021%20@%2016-44

**Comment by LuzRod123** [comment]
maybe it's because i'm not a the last version of acnh ?

**Comment by Ixaruz** [comment]
you have to be on the same version (or higher) of the save you're trying to load, yes.

**Comment by LuzRod123** [comment]
Oh okay thx for everything i update my game and it's working
