### ISSUE TITLE
Dream Request: DA-7477-5171-3499

### ISSUE THREAD

**Issue by sonyrich** [Ixaruz/Luna-Archive-of-Dreams#76]
As title, would you like to dump the map for me?
Thanks
Code: DA-7477-5171-3499
Source vid: https://www.youtube.com/watch?v=xb0qhWAYb4I

**Comment by somegenie** [comment]
I checked that dream address and unfortunately that video is very outdated. The layout of the island is completely different now, everything is changed and it's in winter. I've dumped it anyway if you're still interested. Just need to know the right way to put the files here (I'm new sorry).

**Comment by sonyrich** [comment]
if so I'll close this issue now.
Thanks for inform the the info :>
