### ISSUE TITLE
Dreams

### ISSUE THREAD

**Issue by Nowanoire** [Ixaruz/Luna-Archive-of-Dreams#77]
Hi,

could you do these please?

Euphoria Island : DA-2700-6919-8672

Birth: DA-3778-5749-2813

**Comment by somegenie** [comment]
OK, done! (Though I'm not the owner...) I'll share them when I'm less new to GitHub and learn what to do... Sorry for the delay.

**Comment by Ixaruz** [comment]
added to the archive.
