### ISSUE TITLE
Dump request

### ISSUE THREAD

**Issue by shamppoo** [Ixaruz/Luna-Archive-of-Dreams#8]
Hi, banned switch here! I’d like this island, please:
DA-2352-7745-4698

Thank you ♥♥

**Comment by Ixaruz** [comment]
The save wasn't tested yet but it is assumed working by my critical eye. You can find your save here:
https://github.com/Ixaruz/Luna-Archive-of-Dreams/tree/master/1.9.0

I had to zip it, due to github being a total piece of trash on phone.
